/*
 * ChL-CyberKit v1.0 PRO — ESP32 WiFi/BLE Security Auditing Framework
 * Copyright (C) 2026  ChL (Pedro Reza) <pedrorezabala26@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
/**
 * @file page_index.h
 * @brief Panel web ChL-CyberKit v1.0 PRO — dark theme, estilo Marauder/Bruce
 *        Servido como HTML plano (sin gzip) desde el webserver.
 * @author Pedro Luis Rezabala — ChL-CyberKit v1.0 PRO
 */
#pragma once

/* Served directly — webserver MUST NOT set Content-Encoding: gzip */
static const char PAGE_INDEX_HTML[] =
"<!DOCTYPE html><html lang='es'><head>"
"<meta charset='UTF-8'><meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>ChL-CyberKit PRO</title>"
"<style>"
":root{--bg:#0a0a0f;--panel:#111118;--border:#1e2030;--accent:#00ff88;--accent2:#00ccff;"
"--red:#ff4444;--yellow:#ffcc00;--purple:#cc66ff;--text:#e0e0e0;--muted:#555570;"
"--btn:#1a1a28;--btn-h:#252538;}"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{background:var(--bg);color:var(--text);font-family:'Courier New',monospace;font-size:13px}"
"header{background:#0d0d1a;border-bottom:1px solid var(--accent);padding:10px 16px;"
"display:flex;align-items:center;justify-content:space-between}"
"header h1{color:var(--accent);font-size:16px;letter-spacing:2px}"
"header .status-dot{width:8px;height:8px;border-radius:50%;display:inline-block;margin-right:6px}"
".dot-g{background:var(--accent);box-shadow:0 0 6px var(--accent)}"
".dot-r{background:var(--red);box-shadow:0 0 6px var(--red)}"
".dot-y{background:var(--yellow);box-shadow:0 0 6px var(--yellow)}"
".dot-p{background:var(--purple);box-shadow:0 0 6px var(--purple)}"
"nav{display:flex;background:#0d0d1a;border-bottom:1px solid var(--border);overflow-x:auto}"
"nav button{background:none;border:none;color:var(--muted);padding:10px 16px;"
"cursor:pointer;font-family:inherit;font-size:12px;letter-spacing:1px;white-space:nowrap;"
"border-bottom:2px solid transparent;transition:.2s}"
"nav button.active{color:var(--accent);border-bottom-color:var(--accent)}"
"nav button:hover{color:var(--text)}"
"main{padding:12px;max-width:900px;margin:0 auto}"
".grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:10px;margin-bottom:10px}"
".card{background:var(--panel);border:1px solid var(--border);border-radius:6px;padding:12px}"
".card h3{color:var(--accent2);font-size:11px;letter-spacing:2px;margin-bottom:10px;text-transform:uppercase}"
".row{display:flex;align-items:center;justify-content:space-between;margin:6px 0;gap:8px}"
".label{color:var(--muted);font-size:11px;flex-shrink:0}"
".val{color:var(--text);font-size:12px;text-align:right;word-break:break-all}"
".val-g{color:var(--accent)}"
".val-r{color:var(--red)}"
".val-y{color:var(--yellow)}"
".val-p{color:var(--purple)}"
".badge{display:inline-block;padding:2px 8px;border-radius:10px;font-size:10px;font-weight:bold}"
".badge-g{background:#003322;color:var(--accent);border:1px solid var(--accent)}"
".badge-r{background:#330011;color:var(--red);border:1px solid var(--red)}"
".badge-y{background:#332200;color:var(--yellow);border:1px solid var(--yellow)}"
".badge-b{background:#001133;color:var(--accent2);border:1px solid var(--accent2)}"
".badge-p{background:#220033;color:var(--purple);border:1px solid var(--purple)}"
".badge-m{background:#1a1a1a;color:var(--muted);border:1px solid var(--muted)}"
"btn,button.btn{display:inline-block;background:var(--btn);border:1px solid var(--border);"
"color:var(--text);padding:6px 12px;border-radius:4px;cursor:pointer;font-family:inherit;"
"font-size:12px;transition:.2s;text-decoration:none}"
"button.btn:hover{background:var(--btn-h);border-color:var(--muted)}"
"button.btn-g{border-color:var(--accent);color:var(--accent)}"
"button.btn-g:hover{background:#003322}"
"button.btn-r{border-color:var(--red);color:var(--red)}"
"button.btn-r:hover{background:#330011}"
"button.btn-y{border-color:var(--yellow);color:var(--yellow)}"
"button.btn-b{border-color:var(--accent2);color:var(--accent2)}"
"button.btn-p{border-color:var(--purple);color:var(--purple)}"
"button.btn-p:hover{background:#220033}"
"select,input[type=number],input[type=text]{background:var(--btn);border:1px solid var(--border);"
"color:var(--text);padding:5px 8px;border-radius:4px;font-family:inherit;font-size:12px;"
"width:100%}"
"select:focus,input:focus{outline:none;border-color:var(--accent)}"
".section{display:none}.section.active{display:block}"
"table{width:100%;border-collapse:collapse;font-size:11px}"
"th{color:var(--muted);text-align:left;padding:6px 8px;border-bottom:1px solid var(--border);"
"font-weight:normal;letter-spacing:1px}"
"td{padding:5px 8px;border-bottom:1px solid #1a1a22;vertical-align:top}"
"tr:hover td{background:#0d0d18}"
".ap-row{cursor:pointer}"
".ap-row.selected{background:#001122!important}"
".ap-row.selected td{color:var(--accent2)}"
".console{background:#050508;border:1px solid var(--border);border-radius:4px;"
"padding:10px;height:200px;overflow-y:auto;font-size:11px;line-height:1.6}"
".console-line{padding:1px 0}"
".console-line.info{color:var(--accent)}"
".console-line.warn{color:var(--yellow)}"
".console-line.err{color:var(--red)}"
".progress-bar{background:#1a1a22;border-radius:3px;height:6px;margin:4px 0}"
".progress-fill{height:100%;border-radius:3px;background:var(--accent);transition:.5s}"
"#toast{position:fixed;bottom:20px;right:20px;background:#1a1a28;border:1px solid var(--accent);"
"color:var(--accent);padding:10px 16px;border-radius:6px;display:none;z-index:999;"
"font-size:12px}"
".tool-row{display:flex;gap:8px;margin:8px 0;flex-wrap:wrap;align-items:center}"
".sep{border:none;border-top:1px solid var(--border);margin:10px 0}"
"a{color:var(--accent2);text-decoration:none}"
"a:hover{text-decoration:underline}"
"@media(max-width:480px){nav button{padding:8px 10px;font-size:11px}}"
"</style></head><body>"

"<header>"
"<h1>&#9762; ChL-CyberKit <span style='color:var(--accent2)'>PRO</span></h1>"
"<div style='display:flex;gap:12px;align-items:center'>"
"<span id='hdr-state'><span class='status-dot dot-g'></span>LISTO</span>"
"<span id='hdr-ip' style='color:var(--muted);font-size:11px'>10.10.10.26</span>"
"</div>"
"</header>"

"<nav>"
"<button class='active' onclick='showTab(0)'>PANEL</button>"
"<button onclick='showTab(1)'>WIFI ATAQUES</button>"
"<button onclick='showTab(2)'>HERRAMIENTAS</button>"
"<button onclick='showTab(3)'>DATOS</button>"
"<button onclick='showTab(4)'>ARCHIVOS</button>"
"</nav>"

"<main>"

/* ══════════════════════════════ TAB 0: PANEL ══════════════════════════════ */
"<div id='tab0' class='section active'>"
"<div class='grid'>"

"<div class='card'>"
"<h3>Estado del Sistema</h3>"
"<div class='row'><span class='label'>Uptime</span><span class='val' id='uptime'>--</span></div>"
"<div class='row'><span class='label'>Clientes AP</span><span class='val' id='clients'>--</span></div>"
"<div class='row'><span class='label'>Capturas SD</span><span class='val' id='captures'>--</span></div>"
"<div class='row'><span class='label'>Ataque WiFi</span><span id='atk-state' class='badge badge-m'>IDLE</span></div>"
"</div>"

"<div class='card'>"
"<h3>Herramientas Activas</h3>"
"<div class='row'><span class='label'>Beacon Flood</span><span id='bf-state-p' class='badge badge-m'>IDLE</span></div>"
"<div class='row'><span class='label'>Evil Twin</span><span id='et-state-p' class='badge badge-m'>IDLE</span></div>"
"<div class='row'><span class='label'>Karma Attack</span><span id='ka-state-p' class='badge badge-m'>IDLE</span></div>"
"<div class='row'><span class='label'>Auto Audit</span><span id='aa-state-p' class='badge badge-m'>IDLE</span></div>"
"<div class='row'><span class='label'>BLE Scanner</span><span id='ble-state-p' class='badge badge-m'>IDLE</span></div>"
"</div>"

"<div class='card'>"
"<h3>Detección</h3>"
"<div class='row'><span class='label'>Redes WiFi</span><span class='val' id='net-count'>--</span></div>"
"<div class='row'><span class='label'>Probe Devices</span><span class='val' id='probe-count-p'>--</span></div>"
"<div class='row'><span class='label'>BLE Devices</span><span class='val' id='ble-count-p'>--</span></div>"
"<div class='row'><span class='label'>Karma Respuestas</span><span class='val' id='karma-resp'>--</span></div>"
"<div class='row'><span class='label'>ET Credenciales</span><span class='val' id='et-creds-p'>--</span></div>"
"</div>"

"</div>"/* grid */

"<div class='card'><h3>Acciones Rápidas</h3>"
"<div class='tool-row'>"
"<button class='btn btn-g' onclick='postAPI(\"/api/bf/start\",{channel:6,rate_ms:50},\"BF iniciado\")'>&#9654; Beacon Flood</button>"
"<button class='btn btn-r' onclick='postAPI(\"/api/bf/stop\",{},\"BF detenido\")'>&#9632; BF Stop</button>"
"<button class='btn btn-p' onclick='postAPI(\"/api/karma/start\",{},\"Karma iniciado\")'>&#9670; Karma</button>"
"<button class='btn btn-r' onclick='postAPI(\"/api/karma/stop\",{},\"Karma detenido\")'>&#9632; Karma Stop</button>"
"<button class='btn btn-b' onclick='postAPI(\"/api/ble/start\",{},\"BLE scan iniciado\")'>&#8987; BLE Scan</button>"
"<button class='btn btn-r' onclick='postAPI(\"/api/ble/stop\",{},\"BLE scan detenido\")'>&#9632; BLE Stop</button>"
"</div></div>"
"</div>"/* tab0 */

/* ══════════════════════════════ TAB 1: WIFI ATAQUES ════════════════════════ */
"<div id='tab1' class='section'>"
"<div class='grid'>"

"<div class='card' style='grid-column:1/-1'>"
"<h3>Redes WiFi</h3>"
"<div class='tool-row'>"
"<button class='btn btn-g' onclick='doScan()'>&#128269; Escanear</button>"
"<span class='label' id='net-scan-info'></span>"
"</div>"
"<div style='overflow-x:auto;margin-top:8px'>"
"<table id='ap-table'>"
"<thead><tr><th>#</th><th>SSID</th><th>CH</th><th>RSSI</th><th>AUTH</th><th>VENDOR</th></tr></thead>"
"<tbody id='ap-tbody'><tr><td colspan='6' style='color:var(--muted);text-align:center'>Presiona ESCANEAR</td></tr></tbody>"
"</table></div></div>"

"<div class='card'>"
"<h3>Configurar Ataque</h3>"
"<div class='row'><span class='label'>Target:</span>"
"<span class='val' id='sel-ssid' style='color:var(--accent2)'>-- sin selección --</span></div>"
"<div class='row'><span class='label'>Tipo</span>"
"<select id='atk-type'>"
"<option value='1'>Handshake Capture</option>"
"<option value='2'>PMKID</option>"
"<option value='3'>DoS / Deauth</option>"
"<option value='0'>Pasivo (Monitor)</option>"
"</select></div>"
"<div class='row'><span class='label'>Método</span>"
"<select id='atk-method'>"
"<option value='0'>Unicast (ap→sta)</option>"
"<option value='1'>Broadcast</option>"
"<option value='2'>Mixto</option>"
"</select></div>"
"<div class='row'><span class='label'>Timeout (s)</span>"
"<input type='number' id='atk-timeout' value='30' min='10' max='120'></div>"
"<div class='tool-row' style='margin-top:10px'>"
"<button class='btn btn-g' onclick='launchAttack()'>&#9658; LANZAR</button>"
"<button class='btn btn-r' onclick='stopAttack()'>&#9632; STOP</button>"
"</div>"
"<div id='atk-status' class='row' style='margin-top:8px'></div>"
"</div>"

"<div class='card'>"
"<h3>Evil Twin</h3>"
"<div class='row'><span class='label'>Estado</span><span id='et-state-2' class='badge badge-m'>IDLE</span></div>"
"<div class='row'><span class='label'>Target</span><span class='val' id='et-target'>--</span></div>"
"<div class='row'><span class='label'>Credenciales</span><span class='val val-g' id='et-creds-2'>0</span></div>"
"<div class='tool-row' style='margin-top:10px'>"
"<button class='btn btn-g' onclick='startET()'>&#9658; Iniciar ET</button>"
"<button class='btn btn-r' onclick='postAPI(\"/api/et/stop\",{},\"ET detenido\")'>&#9632; Stop</button>"
"</div>"
"<div class='label' style='margin-top:6px;font-size:10px'>Requiere target seleccionado en la tabla</div>"
"</div>"

"</div>"/* grid */
"</div>"/* tab1 */

/* ════════════════════════════ TAB 2: HERRAMIENTAS ════════════════════════ */
"<div id='tab2' class='section'>"
"<div class='grid'>"

/* Beacon Flood */
"<div class='card'>"
"<h3>&#128161; Beacon Flood</h3>"
"<div class='row'><span class='label'>Estado</span><span id='bf-state-2' class='badge badge-m'>IDLE</span></div>"
"<div class='row'><span class='label'>Beacons</span><span class='val val-g' id='bf-count'>0</span></div>"
"<div class='row'><span class='label'>Canal</span>"
"<select id='bf-ch'>"
"<option>1</option><option>2</option><option>3</option><option>4</option>"
"<option>5</option><option value='6' selected>6</option><option>7</option>"
"<option>8</option><option>9</option><option>10</option><option>11</option>"
"<option>12</option><option>13</option>"
"</select></div>"
"<div class='row'><span class='label'>Intervalo</span>"
"<select id='bf-rate'>"
"<option value='20'>20ms (más rápido)</option>"
"<option value='50' selected>50ms</option>"
"<option value='100'>100ms</option>"
"<option value='200'>200ms</option>"
"<option value='500'>500ms (lento)</option>"
"</select></div>"
"<div class='tool-row' style='margin-top:10px'>"
"<button class='btn btn-g' onclick='startBF()'>&#9654; Iniciar</button>"
"<button class='btn btn-r' onclick='postAPI(\"/api/bf/stop\",{},\"BF detenido\")'>&#9632; Stop</button>"
"</div></div>"

/* Karma Attack */
"<div class='card'>"
"<h3>&#9670; Karma Attack</h3>"
"<div class='row'><span class='label'>Estado</span><span id='ka-state-2' class='badge badge-m'>IDLE</span></div>"
"<div class='row'><span class='label'>Probes vistos</span><span class='val' id='ka-probes'>0</span></div>"
"<div class='row'><span class='label'>Respuestas</span><span class='val val-p' id='ka-resp-2'>0</span></div>"
"<div class='row'><span class='label'>Último SSID</span><span class='val' id='ka-last-ssid'>--</span></div>"
"<div class='row'><span class='label'>Última STA</span><span class='val' id='ka-last-sta'>--</span></div>"
"<div class='tool-row' style='margin-top:10px'>"
"<button class='btn btn-p' onclick='postAPI(\"/api/karma/start\",{},\"Karma iniciado\")'>&#9670; Iniciar</button>"
"<button class='btn btn-r' onclick='postAPI(\"/api/karma/stop\",{},\"Karma detenido\")'>&#9632; Stop</button>"
"</div>"
"<div class='label' style='font-size:10px;margin-top:6px'>El sniffer debe estar activo (hacer SCAN)</div>"
"</div>"

/* BLE Scanner */
"<div class='card'>"
"<h3>&#8987; BLE Scanner</h3>"
"<div class='row'><span class='label'>Estado</span><span id='ble-state-2' class='badge badge-m'>IDLE</span></div>"
"<div class='row'><span class='label'>Dispositivos</span><span class='val val-b' id='ble-count-2'>0</span></div>"
"<div class='tool-row' style='margin-top:10px'>"
"<button class='btn btn-b' onclick='postAPI(\"/api/ble/start\",{},\"BLE scan iniciado\")'>&#9654; Iniciar</button>"
"<button class='btn btn-r' onclick='postAPI(\"/api/ble/stop\",{},\"BLE scan detenido\")'>&#9632; Stop</button>"
"<button class='btn' onclick='postAPI(\"/api/ble/clear\",{},\"BLE tabla limpiada\")'>&#128465; Limpiar</button>"
"</div></div>"

/* Auto Audit */
"<div class='card'>"
"<h3>&#128202; Auto Audit</h3>"
"<div class='row'><span class='label'>Estado</span><span id='aa-state-2' class='badge badge-m'>IDLE</span></div>"
"<div class='row'><span class='label'>Targets</span><span class='val' id='aa-targets'>0/0</span></div>"
"<div class='row'><span class='label'>Capturas</span><span class='val val-g' id='aa-caps'>0</span></div>"
"<div class='row'><span class='label'>SSID actual</span><span class='val' id='aa-ssid'>--</span></div>"
"<div class='row'><span class='label'>PMF skip</span><span class='val' id='aa-pmf'>0</span></div>"
"<div id='aa-prog-bar' class='progress-bar' style='display:none'><div class='progress-fill' id='aa-fill' style='width:0%'></div></div>"
"<div class='tool-row' style='margin-top:10px'>"
"<button class='btn btn-y' onclick='postAPI(\"/api/audit/toggle\",{},\"Audit toggled\")'>&#9654;/&#9632; Toggle</button>"
"</div></div>"

/* Probe Logger */
"<div class='card'>"
"<h3>&#128246; Probe Sniffer</h3>"
"<div class='row'><span class='label'>Dispositivos</span><span class='val val-b' id='probe-count-2'>0</span></div>"
"<div class='tool-row'>"
"<button class='btn' onclick='postAPI(\"/api/probe/dump\",{},\"Dump a SD OK\")'>&#128190; Dump SD</button>"
"<button class='btn' onclick='postAPI(\"/api/probe/clear\",{},\"Probe limpiado\")'>&#128465; Limpiar</button>"
"<button class='btn btn-b' onclick='showProbeTable()'>&#128270; Ver</button>"
"</div>"
"<div id='probe-mini' style='margin-top:8px;max-height:120px;overflow-y:auto;font-size:10px'></div>"
"</div>"

"</div>"/* grid */
"</div>"/* tab2 */

/* ════════════════════════════ TAB 3: DATOS ═══════════════════════════════ */
"<div id='tab3' class='section'>"
"<div class='card' style='margin-bottom:10px'>"
"<h3>Dispositivos BLE</h3>"
"<div class='tool-row'>"
"<button class='btn btn-b' onclick='loadBLE()'>&#8635; Actualizar</button>"
"<button class='btn' onclick='postAPI(\"/api/ble/clear\",{},\"BLE limpiado\")'>&#128465; Limpiar</button>"
"</div>"
"<div style='overflow-x:auto;margin-top:8px'>"
"<table id='ble-table'><thead><tr>"
"<th>MAC</th><th>Nombre</th><th>RSSI</th><th>Tipo</th><th>Visto</th>"
"</tr></thead><tbody id='ble-tbody'>"
"<tr><td colspan='5' style='color:var(--muted);text-align:center'>Sin datos</td></tr>"
"</tbody></table></div></div>"

"<div class='card' style='margin-bottom:10px'>"
"<h3>Probe Devices</h3>"
"<div class='tool-row'>"
"<button class='btn btn-b' onclick='loadProbe()'>&#8635; Actualizar</button>"
"<button class='btn' onclick='postAPI(\"/api/probe/clear\",{},\"Probe limpiado\")'>&#128465; Limpiar</button>"
"<button class='btn' onclick='postAPI(\"/api/probe/dump\",{},\"Dump SD OK\")'>&#128190; Dump SD</button>"
"</div>"
"<div style='overflow-x:auto;margin-top:8px'>"
"<table id='probe-table'><thead><tr>"
"<th>MAC</th><th>Vendor</th><th>SSIDs buscados</th><th>RSSI</th><th>Visto</th>"
"</tr></thead><tbody id='probe-tbody'>"
"<tr><td colspan='5' style='color:var(--muted);text-align:center'>Sin datos</td></tr>"
"</tbody></table></div></div>"

"<div class='card'>"
"<h3>Credenciales Evil Twin</h3>"
"<div class='tool-row'>"
"<button class='btn btn-b' onclick='loadCreds()'>&#8635; Actualizar</button>"
"</div>"
"<div style='overflow-x:auto;margin-top:8px'>"
"<table id='creds-table'><thead><tr>"
"<th>Tiempo</th><th>Usuario</th><th>Contraseña</th><th>IP</th>"
"</tr></thead><tbody id='creds-tbody'>"
"<tr><td colspan='4' style='color:var(--muted);text-align:center'>Sin capturas</td></tr>"
"</tbody></table></div></div>"
"</div>"/* tab3 */

/* ════════════════════════════ TAB 4: ARCHIVOS ═════════════════════════════ */
"<div id='tab4' class='section'>"
"<div class='card'>"
"<h3>Archivos en SD</h3>"
"<div class='tool-row'>"
"<button class='btn btn-g' onclick='loadFiles()'>&#8635; Actualizar</button>"
"</div>"
"<div style='overflow-x:auto;margin-top:8px'>"
"<table id='files-table'><thead><tr>"
"<th>Archivo</th><th>Tamaño</th><th>Acción</th>"
"</tr></thead><tbody id='files-tbody'>"
"<tr><td colspan='3' style='color:var(--muted);text-align:center'>Cargando...</td></tr>"
"</tbody></table></div></div>"
"</div>"/* tab4 */

"</main>"
"<div id='toast'></div>"

"<script>"
/* ── Variables globales ─ */
"var selectedAP=-1,apList=[];"

/* ── showTab ─ */
"function showTab(n){"
"document.querySelectorAll('.section').forEach(function(s,i){s.classList.toggle('active',i===n)});"
"document.querySelectorAll('nav button').forEach(function(b,i){b.classList.toggle('active',i===n)});"
"if(n===3){loadBLE();loadProbe();loadCreds();}"
"if(n===4){loadFiles();}"
"}"

/* ── Toast ─ */
"function toast(msg,ok){"
"var t=document.getElementById('toast');"
"t.textContent=msg;t.style.borderColor=ok===false?'#ff4444':'#00ff88';"
"t.style.color=ok===false?'#ff4444':'#00ff88';"
"t.style.display='block';setTimeout(function(){t.style.display='none'},2500);}"

/* ── postAPI ─ */
"function postAPI(url,body,msg){"
"fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify(body)})"
".then(function(r){return r.json()})"
".then(function(d){toast(msg||d.msg||'OK',true);setTimeout(updateStatus,400);})"
".catch(function(e){toast('Error: '+e.message,false);});}"

/* ── updateStatus ─ */
"function updateStatus(){"
"fetch('/api/status').then(function(r){return r.json()}).then(function(d){"
/* Panel badges */
"setBadge('bf-state-p',d.bf_state==='RUNNING','badge-g','badge-m');"
"setBadge('et-state-p',d.et_state==='RUNNING','badge-g','badge-m');"
"setBadge('ka-state-p',d.ka_state==='RUNNING','badge-p','badge-m');"
"setBadge('aa-state-p',d.aa_state!=='IDLE','badge-y','badge-m');"
"setBadge('ble-state-p',d.ble_state==='RUNNING','badge-b','badge-m');"
/* Tool tab badges */
"setBadge('bf-state-2',d.bf_state==='RUNNING','badge-g','badge-m');"
"setBadge('et-state-2',d.et_state==='RUNNING','badge-g','badge-m');"
"setBadge('ka-state-2',d.ka_state==='RUNNING','badge-p','badge-m');"
"setBadge('aa-state-2',d.aa_state!=='IDLE','badge-y','badge-m');"
"setBadge('ble-state-2',d.ble_state==='RUNNING','badge-b','badge-m');"
/* Text values */
"setText('uptime',fmtTime(d.uptime_s));"
"setText('clients',d.clients);"
"setText('captures',d.captures);"
"setText('net-count',d.net_count);"
"setText('probe-count-p',d.probe_count);"
"setText('probe-count-2',d.probe_count);"
"setText('ble-count-p',d.ble_count);"
"setText('ble-count-2',d.ble_count);"
"setText('karma-resp',d.ka_responses);"
"setText('ka-resp-2',d.ka_responses);"
"setText('ka-probes',d.ka_probes);"
"setText('ka-last-ssid',d.ka_last_ssid||'--');"
"setText('ka-last-sta',d.ka_last_sta||'--');"
"setText('et-creds-p',d.et_creds);"
"setText('et-creds-2',d.et_creds);"
"setText('bf-count',d.bf_count);"
"setText('aa-targets',d.aa_done+'/'+d.aa_total);"
"setText('aa-caps',d.aa_caps);"
"setText('aa-ssid',d.aa_ssid||'--');"
"setText('aa-pmf',d.aa_pmf);"
/* Attack state */
"var as=d.atk_state;"
"var ab=document.getElementById('atk-state');"
"if(ab){ab.textContent=as;ab.className='badge '+(as==='RUNNING'?'badge-g':as==='FINISHED'?'badge-b':as==='TIMEOUT'?'badge-r':'badge-m');}"
/* Header state */
"var hs=document.getElementById('hdr-state');"
"var dot=(d.bf_state==='RUNNING'||d.et_state==='RUNNING'||d.ka_state==='RUNNING')?'dot-g':(as==='RUNNING'?'dot-y':'dot-g');"
"if(hs)hs.innerHTML='<span class=\\'status-dot '+dot+'\\'></span>'+(as==='RUNNING'?'ATACANDO':'LISTO');"
/* AA progress */
"var fill=document.getElementById('aa-fill');"
"var pb=document.getElementById('aa-prog-bar');"
"if(fill&&pb){if(d.aa_total>0){pb.style.display='block';fill.style.width=Math.round(d.aa_done*100/d.aa_total)+'%';}else{pb.style.display='none';}}"
"}).catch(function(){});}"

"function setBadge(id,cond,yes,no){"
"var el=document.getElementById(id);if(!el)return;"
"el.textContent=cond?(el.id.indexOf('ka')>=0?'RUNNING':(el.id.indexOf('ble')>=0?'RUNNING':'RUNNING')):'IDLE';"
"el.className='badge '+(cond?yes:no);}"

"function setText(id,v){var el=document.getElementById(id);if(el)el.textContent=v;}"

"function fmtTime(s){"
"var h=Math.floor(s/3600),m=Math.floor((s%3600)/60),ss=s%60;"
"return (h?h+'h ':'')+(m?m+'m ':'')+(ss+'s');}"

/* ── Scan redes ─ */
"function doScan(){"
"document.getElementById('net-scan-info').textContent='Escaneando...';"
"fetch('/run-attack',{method:'GET'});"/* reuse webserver scan via ap-list */
"setTimeout(function(){"
"fetch('/ap-list').then(function(r){return r.arrayBuffer()}).then(parseAPList);"
"},2000);}"

"function parseAPList(buf){"
"var data=new Uint8Array(buf),n=data.length/42;"
"apList=[];var tbody=document.getElementById('ap-tbody');"
"if(n===0){tbody.innerHTML='<tr><td colspan=6 style=color:var(--muted);text-align:center>0 redes</td></tr>';return;}"
"document.getElementById('net-scan-info').textContent=n+' redes';"
"document.getElementById('net-count').textContent=n;"
"tbody.innerHTML='';"
"for(var i=0;i<n;i++){"
"var off=i*42;"
"var ssid='';"
"for(var j=0;j<32;j++){var c=data[off+j];if(c===0)break;ssid+=String.fromCharCode(c);}"
"var ch=data[off+32];"
"var rssi=data[off+33]-256;"/* signed byte */
"var auth=['OPEN','WEP','WPA','WPA2','WPA2E','WPA3','WPA3E'][data[off+34]]||'?';"
"var bssid='';"
"for(var j=0;j<6;j++){if(j)bssid+=':';bssid+=data[off+35+j].toString(16).padStart(2,'0').toUpperCase();}"
"apList.push({ssid:ssid,ch:ch,rssi:rssi,auth:auth,bssid:bssid});"
"var tr=document.createElement('tr');"
"tr.className='ap-row';tr.dataset.idx=i;"
"tr.innerHTML='<td>'+i+'</td><td>'+escH(ssid||'(oculta)')+'</td><td>'+ch+'</td><td>'+rssi+'</td>"
"<td>'+auth+'</td><td>'+bssid.substring(0,8)+'</td>';"
"tr.onclick=function(){selectAP(parseInt(this.dataset.idx));};"
"tbody.appendChild(tr);}}"

"function selectAP(i){"
"selectedAP=i;"
"document.querySelectorAll('.ap-row').forEach(function(r){r.classList.toggle('selected',parseInt(r.dataset.idx)===i)});"
"var ap=apList[i];"
"document.getElementById('sel-ssid').textContent=ap.ssid+' (CH'+ap.ch+')';"
"document.getElementById('et-target').textContent=ap.ssid;}"

/* ── Launch attack ─ */
"function launchAttack(){"
"if(selectedAP<0){toast('Seleccioná una red primero',false);return;}"
"var body={ap_record_id:selectedAP,"
"type:parseInt(document.getElementById('atk-type').value),"
"method:parseInt(document.getElementById('atk-method').value),"
"timeout:parseInt(document.getElementById('atk-timeout').value)};"
"fetch('/run-attack',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})"
".then(function(){toast('Ataque lanzado',true);setTimeout(updateStatus,500);}).catch(function(e){toast('Error '+e,false);});}"

"function stopAttack(){"
"fetch('/reset',{method:'HEAD'}).then(function(){toast('Ataque detenido',true);setTimeout(updateStatus,500);});}"

/* ── Evil Twin ─ */
"function startET(){"
"if(selectedAP<0){toast('Seleccioná una red primero',false);return;}"
"postAPI('/api/et/start',{ap_id:selectedAP},'Evil Twin iniciado');}"

/* ── Beacon Flood ─ */
"function startBF(){"
"var ch=parseInt(document.getElementById('bf-ch').value);"
"var rate=parseInt(document.getElementById('bf-rate').value);"
"postAPI('/api/bf/start',{channel:ch,rate_ms:rate},'Beacon Flood iniciado');}"

/* ── Load tables ─ */
"function loadBLE(){"
"fetch('/api/ble/list').then(function(r){return r.json()}).then(function(d){"
"var tb=document.getElementById('ble-tbody');"
"if(!d.devices||!d.devices.length){tb.innerHTML='<tr><td colspan=5 style=color:var(--muted);text-align:center>Sin dispositivos</td></tr>';return;}"
"tb.innerHTML='';"
"d.devices.forEach(function(dev){"
"var tr=document.createElement('tr');"
"tr.innerHTML='<td style=font-size:10px>'+dev.mac+'</td><td>'+escH(dev.name||'?')+"
"'</td><td>'+dev.rssi+'</td><td>'+(dev.addr_type===0?'PUB':'RND')+'</td><td>'+dev.seen+'</td>';"
"tb.appendChild(tr);});"
"}).catch(function(){});}"

"function loadProbe(){"
"fetch('/api/probe/list').then(function(r){return r.json()}).then(function(d){"
"var tb=document.getElementById('probe-tbody');"
"if(!d.devices||!d.devices.length){tb.innerHTML='<tr><td colspan=5 style=color:var(--muted);text-align:center>Sin dispositivos</td></tr>';return;}"
"tb.innerHTML='';"
"d.devices.forEach(function(dev){"
"var tr=document.createElement('tr');"
"var ssids=dev.ssids?dev.ssids.join(', '):'?';"
"tr.innerHTML='<td style=font-size:10px>'+dev.mac+'</td><td>'+escH(dev.vendor||'?')+"
"'</td><td style=font-size:10px>'+escH(ssids)+'</td><td>'+dev.rssi+'</td><td>'+dev.count+'</td>';"
"tb.appendChild(tr);});"
"}).catch(function(){});}"

"function loadCreds(){"
"fetch('/api/credentials').then(function(r){return r.json()}).then(function(d){"
"var tb=document.getElementById('creds-tbody');"
"if(!d.creds||!d.creds.length){tb.innerHTML='<tr><td colspan=4 style=color:var(--muted);text-align:center>Sin capturas</td></tr>';return;}"
"tb.innerHTML='';"
"d.creds.forEach(function(c){"
"var tr=document.createElement('tr');"
"tr.innerHTML='<td>'+escH(c.ts||'?')+'</td><td style=color:var(--accent)>'+escH(c.user||'?')+"
"'</td><td style=color:var(--red)>'+escH(c.pass||'?')+'</td><td>'+escH(c.ip||'?')+'</td>';"
"tb.appendChild(tr);});"
"}).catch(function(){});}"

"function loadFiles(){"
"fetch('/api/files').then(function(r){return r.json()}).then(function(d){"
"var tb=document.getElementById('files-tbody');"
"if(!d.files||!d.files.length){tb.innerHTML='<tr><td colspan=3 style=color:var(--muted);text-align:center>Sin archivos</td></tr>';return;}"
"tb.innerHTML='';"
"d.files.forEach(function(f){"
"var tr=document.createElement('tr');"
"var sz=f.size>1024?Math.round(f.size/1024)+' KB':f.size+' B';"
"tr.innerHTML='<td>'+escH(f.name)+'</td><td>'+sz+"
"'</td><td><a href=\\'/api/files/dl?path='+encodeURIComponent(f.path)+\\'\\'>&#128229; Descargar</a></td>';"
"tb.appendChild(tr);});"
"}).catch(function(){});}"

"function showProbeTable(){"
"fetch('/api/probe/list').then(function(r){return r.json()}).then(function(d){"
"var el=document.getElementById('probe-mini');el.innerHTML='';"
"if(!d.devices||!d.devices.length){el.textContent='Sin datos';return;}"
"d.devices.slice(0,5).forEach(function(dev){"
"var line=document.createElement('div');"
"line.style.padding='2px 0';line.style.borderBottom='1px solid #1a1a22';"
"line.innerHTML='<span style=color:var(--accent2)>'+dev.mac+'</span> '+escH(dev.vendor||'?')+' '+dev.rssi+'dBm';el.appendChild(line);});});}"

"function escH(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}"

/* ── Auto-poll ─ */
"updateStatus();"
"setInterval(updateStatus,3000);"
"</script></body></html>";

static const size_t PAGE_INDEX_HTML_LEN = sizeof(PAGE_INDEX_HTML) - 1;
